/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GameAiRouteImport } from './routes/game.ai'
import { Route as GameLocalRouteImport } from './routes/game.local'
import { Route as GameOnlineIndexRouteImport } from './routes/game.online.index'
import { Route as GameOnlineCodeRouteImport } from './routes/game.online.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAiRoute = GameAiRouteImport.update({
  id: '/game/ai',
  path: '/game/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLocalRoute = GameLocalRouteImport.update({
  id: '/game/local',
  path: '/game/local',
  getParentRoute: () => rootRouteImport,
} as any)
const GameOnlineIndexRoute = GameOnlineIndexRouteImport.update({
  id: '/game/online/',
  path: '/game/online/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameOnlineCodeRoute = GameOnlineCodeRouteImport.update({
  id: '/game/online/$code',
  path: '/game/online/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/online/$code': typeof GameOnlineCodeRoute
  '/game/online/': typeof GameOnlineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/online/$code': typeof GameOnlineCodeRoute
  '/game/online': typeof GameOnlineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/online/$code': typeof GameOnlineCodeRoute
  '/game/online/': typeof GameOnlineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/game/ai'
    | '/game/local'
    | '/game/online/$code'
    | '/game/online/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/game/ai'
    | '/game/local'
    | '/game/online/$code'
    | '/game/online'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/game/ai'
    | '/game/local'
    | '/game/online/$code'
    | '/game/online/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GameAiRoute: typeof GameAiRoute
  GameLocalRoute: typeof GameLocalRoute
  GameOnlineCodeRoute: typeof GameOnlineCodeRoute
  GameOnlineIndexRoute: typeof GameOnlineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/ai': {
      id: '/game/ai'
      path: '/game/ai'
      fullPath: '/game/ai'
      preLoaderRoute: typeof GameAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/local': {
      id: '/game/local'
      path: '/game/local'
      fullPath: '/game/local'
      preLoaderRoute: typeof GameLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/online/': {
      id: '/game/online/'
      path: '/game/online'
      fullPath: '/game/online/'
      preLoaderRoute: typeof GameOnlineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/online/$code': {
      id: '/game/online/$code'
      path: '/game/online/$code'
      fullPath: '/game/online/$code'
      preLoaderRoute: typeof GameOnlineCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GameAiRoute: GameAiRoute,
  GameLocalRoute: GameLocalRoute,
  GameOnlineCodeRoute: GameOnlineCodeRoute,
  GameOnlineIndexRoute: GameOnlineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
